apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-ayso-grupo-2-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: tp-ayso-grupo-2
        image: Dockerfile
        ports:
        - containerPort: 8080
